### ISSUE TITLE
[Bug] [Metrics] Check result is wrong in formula 'Actual/Expected*100%' when left side value contains decimals

### ISSUE THREAD

**Issue by leeoo** [datavane/datavines#437]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

规则作业检查结果的校验公式那里，会对小数进行四舍五入到整数，比如这个公式左边算出来应该是 76.54，76.54 >= 77.0 公式不成立，结果应该是失败的，但由于四舍五入了，变成了 77.0 就相等了，检查结果就变成功了。
![3ddae6a70bcab255bff5bbc67fec550](https://github.com/user-attachments/assets/433c9354-974a-4bee-a88e-f8b20501e155)

### DataVines Version

branch: dev
version: 1.0.0-SNAPSHOT

### DataVines Config

```conf
See detail in 'What happend'.
```

### Running Command

```shell
See detail in 'What happend'.
```

### Error Exception

```log
No exception, just wrong check result.
```

### Engine Type

local

### Java Version

11

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
this issue has been fixed in #434

**Comment by leeoo** [comment]
I can still reproduce this issue after running the latest dev code.
![1724636638617](https://github.com/user-attachments/assets/bb32bd8c-f044-4a81-be40-dadf4c0b5055)
![图片](https://github.com/user-attachments/assets/e617148f-53d8-4ee0-b09d-2c332489123b)
